version: '2'
services:
    jador-app:
        image: jador
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jador-postgresql:5432/jador
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jador-postgresql:
        extends:
            file: postgresql.yml
            service: jador-postgresql
